import Data.List


letterList = [
  "AAAACCEEEGHKKLLNNOOOOOPRRRSW", -- ACLOCKWORKORANGE ONAPALEHORSE
  "AAACDEEEFGGHHHIIILLNORRRSSSSTTUVWY",
  "BDEEFGGGHIIILLLNOOOORRSSTTUWW",
  "AACCDDEEEEFGGHHHIILNNNOOOOOPPRRRRTTTUY",
  "AABCCEEEEEEEFGHHIILLLLMNNOOPPRRRSTTTW", -- THESCARLETPIMPERNEL
  "AAAAABCDEEEEGHHHIKLLLLMNORSTVWWYY",
  "EEEEEFFFHHIIIILLNNNRRSTTTTTTUUWW", -- WHITETRUFFLESINWINTER
  "AABEEEEGHIIILMMMNNNOOOPRRRSTVVW", -- VAMPIRESINTHELEMONGROVE
  "CDDEEEEEEFGHHHIILLNNOPRRSSSTTTV",
  "ABBBCCDDEEEFGHHHHIIIKLLNOOOPRRSTTTUVW", -- WITCHOFBLACKBIRDPOND
  "DEEEEGGGGHHIIILLLMNNNNOORRSTTTTTY", -- NIGHTYNIGHTLITTLEGREENMONSTER
  "AABCDEEEFGHILMNNNOOOOOORRRSTTTTUW",
  "ACEEEGHHHIIIILMMNNNNPRRSSSTTUVWY",
  "ACCEEEGHHILLLLMOOOOORRSTTWY" -- THEYELLOWROOM
  ]

-- BROWNOWLSGUIDETOLIFE
-- b___ires_o_i_s

contains [] letters = True
contains (c:cs) letters =
    if elem c letters
    then contains cs (delete c letters)
    else False

whatsLeft [] letters = Just letters
whatsLeft (c:cs) letters =
    if elem c letters
    then whatsLeft cs (delete c letters)
    else Nothing
